version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - policy-service-app
  policy-service:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - policy-service-app
    command: bash -c 'bin/setup && rails server -b 0.0.0.0 -p 3000'
networks:
  policy-service-app:
    name: policy-service-app
