default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: police_service_development

test:
  <<: *default
  database: police_service_test
  host: <%= ENV['POSTGRES_HOST'] || 'postgres' %>
  user: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>

production:
  <<: *default
  database: 'police_service'
